In [14]:
import numpy as np
a = [1,1,1,1,1,1]
c = np.zeros_like(a) + a
c = [c,c]
sum(c),c

(array([2, 2, 2, 2, 2, 2]),
 [array([1, 1, 1, 1, 1, 1]), array([1, 1, 1, 1, 1, 1])])

In [9]:
b = [np.zeros_like(a),np.zeros_like(a),np.ones_like(a)]
sum(b)/len(b)

array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333])

In [11]:
c = [[1,1],[2,2]]
sum(c)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [15]:
d = np.array([[1,1],[2,2]])
np.sum(d,axis=0)

array([3, 3])